import Head from 'next/head'
import { icons } from 'react-icons';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillFacebook} from 'react-icons/ai';

import Image from 'next/image';

import deved from '../public/dev-ed-wave.png';
import ht from "../public/ht.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png"
import wd from "../public/wd.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"

import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (

    <div className={darkMode ? "dark" :""}>
      <Head>
        <title>Nasir Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      
  

      <main className='dark:bg-gray-900 md:px-20 lg:px-40'>

      <section className= " min-h-screen">
      <nav className='py-10 mb-10 flex justify-between'>
        <h1 className='text-2xl font-burtons'>DevelopedbyNK</h1>
        <ul className='flex items-center'>
          <li className='cursor-pointer text-2xl'> <BsFillMoonStarsFill onClick={()=> setDarkMode(!darkMode)}/></li>
          <li className='text-white bg-gradient-to-r from-cyan-500 to-teal-500 rounded-md  px-4 py-2 ml-5'> <a href="#">Resume</a></li>
        </ul>
      </nav>

    
    

    <div className='text-center p-10 '>
        <h2 className='text py-2 text-teal-600 font-medium text-5xl md:text-6xl'>Nasir khan</h2>
        <h3 className='text-2xl py-2 md:text-2xl'>Web Developer</h3>
        <p className='text-md py-5 leading-8 text-gray-800'>A <span className='text-teal-500 md:text-xl max-wd-xl max-auto'>Web developer</span> who is always seeking to find the opportunity to work in a fun and challenging
working environment that will encourage me to improve and learn new and necessary skills as well as
motivated by the Market to do my best for the sake of helping others and myself to be
advanced in the software industry.</p>
    </div>

      <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 cursor-pointer mb-2'>
      <AiFillTwitterCircle/>
      <AiFillLinkedin/>
      <AiFillFacebook/>
      </div>

      <div className=' relative mx-auto w-80 h-80 bg-gradient-to-b from-teal-500 rounded-full mt-20 overflow-hidden md:h-96 md:w-96'>
<Image src={deved} layout="fill" objectFit='cover'/>

</div>

   

      </section>
      
     

      <section>
        <div className='py-20 text-center'>
        <h3 className='text-3xl py-1 '>Services I offer</h3>
        <p className='text-md py-1 leading-8 text-gray-800'>Since beginning of my journey as a freelancer and Web developer. 
        I've done remote work for <span className='text-teal-500'>Agencies </span>  
        consulted for new <span className='text-teal-500'>startups</span> and callaborated with talented people
        to make beautiful design for business and consumer use.</p>

        <p className='text-md py-1 leading-8 text-gray-800'>I offer a wide range of services,
         Including programming and teaching. </p>

        </div>
      

        <div className='lg:flex gap-16'>
          <div className=' text-center shadow-lg p-10 rounded-lg my-10'>
            <Image src={ht} width={100} height={100}/>
            <h3 className='text-lg font-md pt-8 pb-2'>HTML</h3>
            <p className='py-2'>Creating elegant design suitable for your business needs</p>
            <h4 className='text-teal-400 py-4'>Design tools I use</h4>
            <p className='text-gray-500 py-1'>Photoshop</p>
            <p className="text-gray-500 py-1">Illustrator</p>
            <p className='text-gray-500 py-1'>Figma</p>                    

          </div>
          <div className=' text-center shadow-lg p-10 rounded-lg my-10'>
            <Image src={code} width={100} height={100}/>
            <h3 className='text-lg font-md pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2'>Creating elegant design suitable for your business needs</p>
            <h4 className='text-teal-400 py-4'>Design tools I use</h4>
            <p className='text-gray-500 py-1'>Photoshop</p>
            <p className="text-gray-500 py-1">Illustrator</p>
            <p className='text-gray-500 py-1'>Figma</p>                    

          </div>

          <div className=' text-center shadow-lg p-10 rounded-lg my-10'>
            <Image src={consulting} width={100} height={100}/>
            <h3 className='text-lg font-md pt-8 pb-2'>Beautiful Designs</h3>
            <p className='py-2'>Creating elegant design suitable for your business needs</p>
            <h4 className='text-teal-400 py-4'>Design tools I use</h4>
            <p className='text-gray-500 py-1'>Photoshop</p>
            <p className="text-gray-500 py-1">Illustrator</p>
            <p className='text-gray-500 py-1'>Figma</p>                    

          </div>


        </div>
      
      <section>
      <div className='py-20 text-center'>
        <h3 className='text-3xl py-1 '>Portfolio</h3>
        <p className='text-md py-1 leading-8 text-gray-800'>Since beginning of my journey as a freelancer and Web developer. 
        I've done remote work for <span className='text-teal-500'>Agencies </span>  
        consulted for new <span className='text-teal-500'>startups</span> and callaborated with talented people
        to make beautiful design for business and consumer use.</p>

        <p className='text-md py-1 leading-8 text-gray-800'>I offer a wide range of services,
         Including programming and teaching. </p>

        </div>

        <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
          <div className='basis 1/3 flex-1 '><Image src={wd} className="rounded-lg object-cover" width={"100"} height={'100'} layout='responsive'/></div>
          <div className='basis 1/3 flex-1 '><Image src={web2} className="rounded-lg object-cover" width={"100"} height={'100'} layout='responsive'/></div>
          <div className='basis 1/3 flex-1 '><Image src={web3} className="rounded-lg object-cover" width={"100"} height={'100'} layout='responsive'/></div>
          <div className='basis 1/3 flex-1 '><Image src={web4} className="rounded-lg object-cover" width={"100"} height={'100'} layout='responsive'/></div>
          <div className='basis 1/3 flex-1'><Image src={web6}  className="rounded-lg object-cover" width={'100'} height={'100'} layout='responsive'/></div>
        </div>
      </section>
             
            
                               
           
        
   

          

         

            
          
            

          

          
            
          
       
       
  
      </section>

    
      </main>

     
    </div>
  )
}
